"""Add speciality column to doctor table

Revision ID: 465fb7fd0188
Revises: df9852cdc94c
Create Date: 2024-11-15 23:50:27.379846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '465fb7fd0188'
down_revision = 'df9852cdc94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('speciality', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('speciality')

    # ### end Alembic commands ###
