"""Change appointment_time and appointment_date data types

Revision ID: 8e2b61d62eb9
Revises: df9852cdc94c
Create Date: 2024-11-15 09:46:11.400602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e2b61d62eb9'
down_revision = 'df9852cdc94c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointment_time',
               existing_type=sa.DATETIME(),
               type_=sa.Time(),
               existing_nullable=False)
        batch_op.alter_column('appointment_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.alter_column('appointment_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               existing_nullable=False)
        batch_op.alter_column('appointment_time',
               existing_type=sa.Time(),
               type_=sa.DATETIME(),
               existing_nullable=False)

    # ### end Alembic commands ###
